apiVersion: v1
kind: Service
metadata:
  name: hello-world-cluster-ip-service-dev
spec:
  type: ClusterIP
  selector:
    app: hello-world
    environment: dev
  ports:
    - port: 80
      targetPort: 80